databases:
  - name: senzoku-hisyoko
    databaseName: hisyoko_db_di1m
    user: senzoku_hisyoko
    region: singapore

services:
  - type: web
    name: senzoku-hisyoko
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails7_sample_staging
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
